---
services:
  fullbogons:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - "BIRD_ROUTER_ID=10.1.2.3"
      - "BIRD_ASN=64666"
      - "BIRD_PEERS=fake_host,10.3.2.1"
      - "BIRD_EXCLUDED_PREFIXES=10.0.0.0/8;172.16.0.0/12;192.168.0.0/16"
    networks:
      - fullbogons
  test:
    command: /bin/bash -c "sleep 60 && apt-get update && apt-get --no-install-recommends --yes install netcat-openbsd && nc -zv fullbogons 179"
    depends_on:
      - fullbogons
    image: "debian:12-slim@sha256:40b107342c492725bc7aacbe93a49945445191ae364184a6d24fedb28172f6f7"
    networks:
      - fullbogons
networks:
  fullbogons:
