---
services:
  stun:
    image: 'ghcr.io/mattkobayashi/stun:v2024.09.0'
    restart: unless-stopped
    ports:
      - target: 3478
        published: 3478
        protocol: tcp
        mode: host
      - target: 3478
        published: 3478
        protocol: udp
        mode: host
