---
services:
  verlihub:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_BIND_SERVICE
    container_name: verlihub
    depends_on:
      verlihub-mysql:
        condition: service_healthy
    environment:
      - 'MYSQL_DB_HOST=verlihub-mysql'
      - 'MYSQL_DB_NAME=verlihub'
      - 'MYSQL_USER=verlihub'
      - 'VH_CONFIG_DIR=/opt/verlihub/.config/verlihub'
      - 'VH_HUB_HOST=verlihub'
      - 'VH_HUB_PORT=411'
      - 'VH_HUB_NAME=Verlihub Test'
      - 'VH_MASTER_NAME=MattK'
    ports:
      - mode: host
        protocol: tcp
        published: 411
        target: 411
      - mode: host
        protocol: udp
        published: 411
        target: 411
    restart: unless-stopped
    secrets:
      - MYSQL_PASSWORD
      - VH_MASTER_PASSWORD
    volumes:
      - source: verlihub-data
        target: /opt/verlihub/.config/verlihub
        type: volume
  verlihub-mysql:
    container_name: verlihub-mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD'
      - 'MYSQL_DATABASE=verlihub'
      - 'MYSQL_USER=verlihub'
      - 'MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD'
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 10s
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
    image: mariadb:11.5.2-ubi9
    restart: unless-stopped
    secrets:
      - MYSQL_PASSWORD
    volumes:
      - source: verlihub-mysql-data
        target: /var/lib/mysql
        type: volume
secrets:
  MYSQL_PASSWORD:
    file: secrets/MYSQL_PASSWORD
  VH_MASTER_PASSWORD:
    file: secrets/VH_MASTER_PASSWORD
volumes:
  verlihub-data:
    name: verlihub-data
  verlihub-mysql-data:
    name: verlihub-mysql-data
