---
name: vyos-release-alert

services:
  ## vyos-release-alert ##
  vyos-release-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vyos-release-alert
    networks:
      - vyos-release-alert
    restart: unless-stopped
networks:
  vyos-release-alert:
    name: vyos-release-alert
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.12.0.0/24
        - subnet: fdea:420:cafe::/64
