---
services:
  certbot-cloudflare:
    image: 'ghcr.io/mattkobayashi/certbot-cloudflare:v2024.09.1'
    restart: unless-stopped
    environment:
      - 'EMAIL='
      - 'DOMAIN='
    secrets:
      - CERTBOT_CF_DNS_API_TOKEN

secrets:
  CERTBOT_CF_DNS_API_TOKEN:
    file: ${PWD}/secrets/CERTBOT_CF_DNS_API_TOKEN  # Set this to the path on the host to your CERTBOT_CF_DNS_API_TOKEN secret file
