---
services:
  actions-runner:
    image: 'ghcr.io/mattkobayashi/actions-runner:latest'
    hostname: 'actions-runner'
    restart: unless-stopped
    environment:
      - 'REPO='
    secrets:
      - TOKEN
