---
all:
  children:
    ios:
      hosts:
        example1.router.com:
          ansible_host: 192.168.0.1
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_become: true
        ansible_become_method: enable
        ansible_user:
        ansible_ssh_pass:
        ansible_ssh_host_key_checking: false
        ansible_host_key_auto_add: true
    iosxr:
      hosts:
        example2.router.com:
          ansible_host: 192.168.1.1
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        ansible_become: true
        ansible_become_method: enable
        ansible_user:
        ansible_ssh_pass:
        ansible_ssh_host_key_checking: false
        ansible_host_key_auto_add: true
    junos:
      hosts:
        example3.router.com:
          ansible_host: 192.168.2.1
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: junipernetworks.junos.junos
        ansible_user:
        ansible_ssh_pass:
        ansible_ssh_host_key_checking: false
        ansible_host_key_auto_add: true
    routeros:
      hosts:
        example.router.com:
          ansible_host: 192.168.3.1
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: community.routeros.routeros
        ansible_user:
        ansible_ssh_pass:
        ansible_ssh_host_key_checking: false
        ansible_host_key_auto_add: true
