---
- name: Clone/update Git repository
  hosts: localhost

  tasks:
    - name: Clone/update Git repository
      ansible.builtin.git:
        repo: https://{{ github_token }}@github.com/{{ github_repo }}
        dest: /repo/

    - name: Configure Git username
      community.general.git_config:
        repo: /repo/
        name: user.name
        scope: local
        value: "{{ git_user }}"

    - name: Configure Git user email
      community.general.git_config:
        repo: /repo/
        name: user.email
        scope: local
        value: "{{ git_email }}"
