---
services:
  yancobat:
    image: 'ghcr.io/mattkobayashi/yancobat:latest'
    restart: unless-stopped
    environment:
      - 'TZ='
      - 'GIT_USER='
      - 'GIT_EMAIL='
      - 'DEVICE_USER='
      - 'DEVICE_PASS='
      - 'GITHUB_REPO='
      - 'NOTIFY_TELEGRAM='
      - 'NOTIFY_TELEGRAM_CHAT_ID='
      - 'NOTIFY_SLACK='
      - 'NOTIFY_SLACK_CHANNEL='

secrets:
  GITHUB_TOKEN:
    file: ${PWD}/secrets/GITHUB_TOKEN  # Set this to the path on the host to your GITHUB_TOKEN secret file
  NOTIFY_TELEGRAM_TOKEN:
    file: ${PWD}/secrets/NOTIFY_TELEGRAM_TOKEN  # Set this to the path on the host to your NOTIFY_TELEGRAM_TOKEN secret file
  NOTIFY_SLACK_TOKEN:
    file: ${PWD}/secrets/NOTIFY_SLACK_TOKEN  # Set this to the path on the host to your NOTIFY_SLACK_TOKEN secret file
