---
services:
  yancobat:
    image: 'ghcr.io/mattkobayashi/yancobat:v2024.09.0'
    restart: unless-stopped
    environment:
      - 'TZ='
      - 'GIT_USER='
      - 'GIT_EMAIL='
      - 'DEVICE_USER='
      - 'GITHUB_REPO='
      - 'NOTIFY_TELEGRAM_ENABLED='
      - 'NOTIFY_TELEGRAM_CHAT_ID='
      - 'NOTIFY_SLACK_ENABLED='
      - 'NOTIFY_SLACK_CHANNEL_ID='
    secrets:
      - DEVICE_PASS
      - GITHUB_TOKEN
      - NOTIFY_TELEGRAM_TOKEN
      - NOTIFY_SLACK_TOKEN

secrets:
  DEVICE_PASS:
    file: ${PWD}/secrets/DEVICE_PASS  # Set this to the path on the host to your DEVICE_PASS secret file
  GITHUB_TOKEN:
    file: ${PWD}/secrets/GITHUB_TOKEN  # Set this to the path on the host to your GITHUB_TOKEN secret file
  NOTIFY_TELEGRAM_TOKEN:
    file: ${PWD}/secrets/NOTIFY_TELEGRAM_TOKEN  # Set this to the path on the host to your NOTIFY_TELEGRAM_TOKEN secret file
  NOTIFY_SLACK_TOKEN:
    file: ${PWD}/secrets/NOTIFY_SLACK_TOKEN  # Set this to the path on the host to your NOTIFY_SLACK_TOKEN secret file
