---
all:
  vars:
    git_user: "{{ lookup('ansible.builtin.env', 'GIT_USER') }}"
    git_email: "{{ lookup('ansible.builtin.env', 'GIT_EMAIL') }}"
    device_user: "{{ lookup('ansible.builtin.env', 'DEVICE_USER') }}"
    device_pass: "{{ lookup('file', '/run/secrets/DEVICE_PASS') }}"
    github_repo: "{{ lookup('ansible.builtin.env', 'GITHUB_REPO') }}"
    github_token: "{{ lookup('file', '/run/secrets/GITHUB_TOKEN') }}"
    notify_pushover_enabled: "{{ lookup('ansible.builtin.env', 'NOTIFY_PUSHOVER_ENABLED') | bool }}"
    notify_pushover_app_token: "{{ lookup('file', '/run/secrets/NOTIFY_PUSHOVER_APP_TOKEN') }}"
    notify_pushover_user_key: "{{ lookup('ansible.builtin.env', 'NOTIFY_PUSHOVER_USER_KEY') }}"
    notify_slack_enabled: "{{ lookup('ansible.builtin.env', 'NOTIFY_SLACK_ENABLED') | bool }}"
    notify_slack_channel_id: "{{ lookup('ansible.builtin.env', 'NOTIFY_SLACK_CHANNEL_ID') }}"
    notify_slack_token: "{{ lookup('file', '/run/secrets/NOTIFY_SLACK_TOKEN') }}"
    notify_telegram_enabled: "{{ lookup('ansible.builtin.env', 'NOTIFY_TELEGRAM_ENABLED') | bool }}"
    notify_telegram_chat_id: "{{ lookup('ansible.builtin.env', 'NOTIFY_TELEGRAM_CHAT_ID') }}"
    notify_telegram_token: "{{ lookup('file', '/run/secrets/NOTIFY_TELEGRAM_TOKEN') }}"
