---
name: Build and publish container images

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  create-runners:
    name: Create self-hosted Actions runners
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        runner-name: [
          actions-runner,
          avahi,
          certbot-cloudflare,
          fullbogons,
          growatt-ev,
          iperf2,
          iperf3,
          irrd,
          mdns-reflector,
          rng-tools,
          speedtest,
          stun,
          telegraf,
          verlihub,
          vyos-release-alert,
          xteve,
          yancobat
        ]
    uses: ./.github/workflows/create-runner.yaml
  build-setup:
    name: Set up build environment
    runs-on: ubuntu-latest
    outputs:
      repo-owner: ${{ steps.repo-lowercase.outputs.REPO_OWNER }}
    steps:
      - name: Convert repository owner name to lowercase
        id: repo-lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
  build-publish:
    name: Build and push
    runs-on: self-hosted
    needs: [create-runners, build-setup]
    strategy:
      fail-fast: false
      matrix:
        container: [
          actions-runner,
          avahi,
          certbot-cloudflare,
          fullbogons,
          growatt-ev,
          iperf2,
          iperf3,
          irrd,
          mdns-reflector,
          rng-tools,
          speedtest,
          stun,
          telegraf,
          verlihub,
          vyos-release-alert,
          xteve,
          yancobat
        ]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          buildkitd-config-inline: |
            [registry."docker.io"]
              mirrors = ["registry-mirror:5000"]
            [registry."registry-mirror:5000"]
              http = true
          driver-opts: |
            network=mattflix
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ needs.build-setup.outputs.repo-owner }}/${{ matrix.container }}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./${{ matrix.container }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
