---
name: Create ephemeral GitHub Actions self-hosted runner

on:
  workflow_call:

jobs:
  create-runner:
    name: 'Create ephemeral runner'
    runs-on: ubuntu-latest
    steps:
      - name: 'Create ephemeral Tailscale node'
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.74.1
      - name: 'Update SSH known hosts'
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          cat << EOF >> ~/.ssh/known_hosts
          $SSH_KNOWN_HOSTS
          EOF
          chmod 600 ~/.ssh/known_hosts
      - name: 'Start ephemeral runner container'
        run: |
          set -eux
          ssh matthew@100.102.37.118 docker container run \
              --cgroupns=private \
              --cgroup-parent=/mattflix/actions-runners \
              --detach \
              --env='APP_ID=${{ secrets.GH_APP_ID }}' \
              --env='APP_LOGIN=${{ secrets.GH_APP_CLIENT_ID }}' \
              --env='APP_PRIVATE_KEY="${{ secrets.GH_APP_PRIVATE_KEY }}"' \
              --env='EPHEMERAL=true' \
              --env='LABELS=linux,x64' \
              --env='REPO_URL=${{ github.server_url }}/${{ github.repository }}' \
              --env='RUNNER_NAME_PREFIX=${{ matrix.container }}' \
              --log-driver=syslog \
              --log-opt='syslog-address=udp://127.0.0.1:55514' \
              --log-opt='syslog-format=rfc5424micro' \
              --log-opt='mode=non-blocking' \
              --log-opt='tag={{.Name}}-mattflix' \
              --network=mattflix \
              --restart=no \
              --security-opt='label=disable' \
              --stop-signal=SIGTERM \
              --stop-timeout=10 \
              ghcr.io/myoung34/docker-github-actions-runner:debian-bookworm
