---
name: Publish images to GHCR.io

on:
  schedule:
    - cron: '0 3 * * SAT'
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-setup:
    runs-on: self-hosted

    steps:
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      - name: Spawn build jobs for each container
        uses: ./.github/workflows/spawn-jobs.yaml
        with:
          repo-owner: ${{ env.REPO_OWNER }}
