---
name: Publish images to GHCR.io

on:
  schedule:
    - cron: '0 3 * * SAT'
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  actions-runner:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  avahi:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  certbot-cloudflare:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  fullbogons:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  growatt-ev:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  iperf2:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  iperf3:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  # irrd:

  #  runs-on: self-hosted
  #  if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
  #  permissions:
  #    contents: read
  #    packages: write

  #  steps:
  #    # Convert the repository owner name to lowercase
  #    - name: Convert repository owner name to lowercase
  #      run: |
  #        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

  #    # Run common jobs
  #    - name: Run common jobs
  #      uses: ./.github/workflows/common-jobs.yaml
  #      with:
  #        image-name: ${{ github.job }}
  #        repo-owner: ${{ env.REPO_OWNER }}

  # irrexplorer:

  #  runs-on: self-hosted
  #  if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
  #  permissions:
  #    contents: read
  #    packages: write

  #  steps:
  #    # Convert the repository owner name to lowercase
  #    - name: Convert repository owner name to lowercase
  #      run: |
  #        echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

  #    # Run common jobs
  #    - name: Run common jobs
  #      uses: ./.github/workflows/common-jobs.yaml
  #      with:
  #        image-name: ${{ github.job }}
  #        repo-owner: ${{ env.REPO_OWNER }}

  mdns-reflector:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  rng-tools:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  speedtest:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  stun:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  telegraf:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  verlihub:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  vyos-blog-alert:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  xteve:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}

  yancobat:

    runs-on: self-hosted
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    permissions:
      contents: read
      packages: write

    steps:
      # Convert the repository owner name to lowercase
      - name: Convert repository owner name to lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> ${GITHUB_ENV}

      # Run common jobs
      - name: Run common jobs
        uses: ./.github/workflows/common-jobs.yaml
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ env.REPO_OWNER }}
