---
name: Spawn Jobs

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string

jobs:
  actions-runner:
    env:
      IMAGE_NAME: actions-runner
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  avahi:
    env:
      IMAGE_NAME: avahi
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  certbot-cloudflare:
    env:
      IMAGE_NAME: certbot-cloudflare
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  fullbogons:
    env:
      IMAGE_NAME: fullbogons
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  growatt-ev:
    env:
      IMAGE_NAME: growatt-ev
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  iperf2:
    env:
      IMAGE_NAME: iperf2
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  iperf3:
    env:
      IMAGE_NAME: iperf3
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  mdns-reflector:
    env:
      IMAGE_NAME: mdns-reflector
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  otbr:
    env:
      IMAGE_NAME: otbr
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}/ot-br-posix/etc/docker/
  rng-tools:
    env:
      IMAGE_NAME: rng-tools
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  speedtest:
    env:
      IMAGE_NAME: speedtest
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  stun:
    env:
      IMAGE_NAME: stun
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  telegraf:
    env:
      IMAGE_NAME: telegraf
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  verlihub:
    env:
      IMAGE_NAME: verlihub
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  vyos-release-alert:
    env:
      IMAGE_NAME: vyos-release-alert
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  xteve:
    env:
      IMAGE_NAME: xteve
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
  yancobat:
    env:
      IMAGE_NAME: yancobat
    if: ${{ github.ref_name == 'main' || contains(github.job, github.head_ref) }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ env.IMAGE_NAME }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ env.IMAGE_NAME }}
