---
name: Spawn Jobs

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string

jobs:
  actions-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  avahi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  certbot-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  fullbogons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  growatt-ev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  iperf2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  iperf3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  mdns-reflector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  otbr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}/ot-br-posix-conditional_avahi/etc/docker/
  rng-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  speedtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  stun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  telegraf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  verlihub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  vyos-release-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  xteve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
  yancobat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: actions/checkout@v4
      - name: Build and push container
        if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
        uses: ./.github/actions/build-and-push
        with:
          image-name: ${{ github.job }}
          repo-owner: ${{ inputs.repo-owner }}
          build-context: ./${{ github.job }}
