---
name: Spawn Jobs

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string

jobs:
  actions-runner:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  avahi:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  certbot-cloudflare:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  fullbogons:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  growatt-ev:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  iperf2:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  iperf3:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  mdns-reflector:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  otbr:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}/ot-br-posix-conditional_avahi/etc/docker/
  rng-tools:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  speedtest:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  stun:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  telegraf:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  verlihub:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  vyos-release-alert:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  xteve:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
  yancobat:
    if: ${{ github.ref_name == 'main' || github.head_ref == vars.GITHUB_JOB }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: ${{ vars.GITHUB_JOB }}
      repo-owner: ${{ inputs.repo-owner }}
      build-context: ./${{ vars.GITHUB_JOB }}
