---
name: Spawn Jobs

on:
  workflow_call:
    inputs:
      repo-owner:
        required: true
        type: string

jobs:
  actions-runner:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: actions-runner
      repo-owner: ${{ inputs.repo-owner }}
  avahi:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: avahi
      repo-owner: ${{ inputs.repo-owner }}
  certbot-cloudflare:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: certbot-cloudflare
      repo-owner: ${{ inputs.repo-owner }}
  fullbogons:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: fullbogons
      repo-owner: ${{ inputs.repo-owner }}
  growatt-ev:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: growatt-ev
      repo-owner: ${{ inputs.repo-owner }}
  iperf2:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: iperf2
      repo-owner: ${{ inputs.repo-owner }}
  iperf3:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: iperf3
      repo-owner: ${{ inputs.repo-owner }}
  mdns-reflector:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: mdns-reflector
      repo-owner: ${{ inputs.repo-owner }}
  rng-tools:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: rng-tools
      repo-owner: ${{ inputs.repo-owner }}
  speedtest:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: speedtest
      repo-owner: ${{ inputs.repo-owner }}
  stun:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: stun
      repo-owner: ${{ inputs.repo-owner }}
  telegraf:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: telegraf
      repo-owner: ${{ inputs.repo-owner }}
  verlihub:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: verlihub
      repo-owner: ${{ inputs.repo-owner }}
  vyos-blog-alert:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: vyos-blog-alert
      repo-owner: ${{ inputs.repo-owner }}
  xteve:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: xteve
      repo-owner: ${{ inputs.repo-owner }}
  yancobat:
    if: ${{ github.ref_name == 'main' || github.head_ref == github.job }}
    uses: ./.github/workflows/build-and-push.yml
    with:
      image-name: yancobat
      repo-owner: ${{ inputs.repo-owner }}
