---
name: Build and test `growatt-ev` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "growatt-ev/**"
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [growatt-ev]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Build and start image
      - name: Build and start image
        run: |
          docker compose up --detach
        working-directory: growatt-ev
      # Wait for container to start and run
      - name: Wait for container to start and run
        run: |
          sleep 60
      # Grab the container logs
      - name: Grab container logs
        run: |
          docker compose logs growatt-ev
        working-directory: growatt-ev
      # Stop and remove containers
      - name: Stop and remove container
        run: |
          docker compose down
        working-directory: growatt-ev
