---
name: Build and test `speedtest` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "speedtest/**"
  workflow_dispatch:

jobs:
  # create-runner:
  #   name: Create self-hosted Actions runner
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Create runner
  #       uses: MattKobayashi/tailscale-qemu-runner-action@v1.7.0
  #       with:
  #         gh-api-token: ${{ secrets.GH_API_TOKEN }}
  #         gha-runner-apt-mirror: http://mirror.overthewire.com.au/ubuntu/
  #         gha-runner-labels: speedtest
  #         gha-runner-tz: Australia/Brisbane
  #         ssh-host: 100.102.37.118
  #         ssh-user: matthew
  #         ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
  #         ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
  #         ts-tag: ci
  build-setup:
    name: Set up build environment
    runs-on: ubuntu-24.04
    outputs:
      repo-owner: ${{ steps.repo-lowercase.outputs.REPO_OWNER }}
    steps:
      - name: Convert repository owner name to lowercase
        id: repo-lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
  build-test:
    name: Build and test image
    # runs-on: speedtest
    runs-on: ubuntu-24.04
    needs: [build-setup]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [speedtest]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      # Test the image
      - name: Test image
        run: |
          docker compose --progress plain up --build --exit-code-from speedtest
        timeout-minutes: 5
        working-directory: ${{ matrix.container }}
