---
name: Build and test `growatt-ev` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "growatt-ev/**"
  workflow_dispatch:

jobs:
  create-runner:
    name: Create self-hosted Actions runner
    runs-on: ubuntu-latest
    steps:
      - name: Create runner
        uses: MattKobayashi/tailscale-qemu-runner-action@v1.6.0
        with:
          gh-api-token: ${{ secrets.GH_API_TOKEN }}
          gha-runner-apt-mirror: http://mirror.overthewire.com.au/ubuntu/
          gha-runner-tz: Australia/Brisbane
          ssh-host: 100.102.37.118
          ssh-user: matthew
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          ts-tag: ci
  build-setup:
    name: Set up build environment
    runs-on: ubuntu-latest
    outputs:
      repo-owner: ${{ steps.repo-lowercase.outputs.REPO_OWNER }}
    steps:
      - name: Convert repository owner name to lowercase
        id: repo-lowercase
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
  build-test:
    name: Build and test image
    runs-on: self-hosted
    needs: [build-setup]
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [growatt-ev]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Build and start image
      - name: Build and start image
        run: |
          set -x
          docker compose up --detach
        working-directory: growatt-ev
      # Wait for container to start and run
      - name: Wait for container to start and run
        run: |
          set -x
          sleep 60
      # Grab the container logs
      - name: Grab container logs
        run: |
          set -x
          docker compose logs growatt-ev
        working-directory: growatt-ev
      # Stop and remove containers
      - name: Stop and remove container
        run: |
          set -x
          docker compose down
        working-directory: growatt-ev
