---
name: Build and test `verlihub` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "verlihub/**"
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [verlihub]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Generate test secrets
      - name: Generate test secrets
        run: |
          mkdir secrets
          echo "sqlpw123" > secrets/VH_MYSQL_PASSWORD
          echo "hubpw123" > secrets/VH_HUB_MASTER_PASSWORD
        working-directory: verlihub
      # Build and start image
      - name: Build and start image
        run: |
          docker compose up --detach
        working-directory: verlihub
      # Grab the container logs
      - name: Grab container logs
        run: |
          sleep 10
          docker compose logs verlihub
        working-directory: verlihub
      # Stop and remove containers
      - name: Stop and remove container
        run: |
          docker compose down
        working-directory: verlihub
