---
name: Build and test `speedtest` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "speedtest/**"
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [speedtest]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      # Test the image
      - name: Test image
        run: |
          docker compose --progress plain up --build --exit-code-from speedtest
        timeout-minutes: 5
        working-directory: ${{ matrix.container }}
