---
name: Build and test `certbot-cloudflare` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "certbot-cloudflare/**"
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [certbot-cloudflare]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3.5.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
      # Test the built image
      - name: Test image
        env:
          CERTBOT_CF_DNS_API_TOKEN: thisisatesttoken
        run: |
          docker compose --progress plain up --build --exit-code-from certbot-cloudflare
        timeout-minutes: 5
        working-directory: ${{ matrix.container }}
