---
name: Build and test `fullbogons` container image

on:
  pull_request:
    branches:
      - main
    paths:
      - "fullbogons/**"
  workflow_dispatch:

jobs:
  build-test:
    name: Build and test image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        container: [fullbogons]
    steps:
      # Checkout repository
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Set up QEMU
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      # Set up Docker Buildx
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      # Test the built image
      - name: Test image
        run: |
          docker compose --progress plain up --build --exit-code-from test
        timeout-minutes: 5
        working-directory: ${{ matrix.container }}
